#!/bin/csh -f
#  makes a tar file BS.tar.Z with all relevant files
   
  echo 'Making tar file for xbs...'

  rm -f BS*.tar*

  set tm = `/bin/date +%b-%d-%Y`
  set file = BS-{$tm}.tar

  tar -cvf $file README License TAR xbs.c intc.c *.h bs_icon *.bs *.mv cx* Cha*

  ls -l {$file}*
  gzip $file
  ls -l {$file}*


