#!/usr/bin/perl

$dir = '/usr/share/doc/xbs/examples'; 

@exs = qw( in alfa bi2201 c60 gray 
           grpht hIII pd8_10 ring
           serp  stb  tic
        );

foreach (@exs)  {

  system "xbs $dir/$_";

}
